name: "Notificar a Teams"
description: "Envía notificaciones a un canal Microsoft Teams"

inputs:
  title:
    description: "Título del mensaje"
    required: true
  message:
    description: "Mensaje que se va a mostrar"
    required: true
  state:
    description: "Estado final (SUCCESS/FAILED)"
    required: true
  color:
    description: "Color del estado (Good/Attention)"
    required: false
    default: "Default"
  action_title:
    description: "Texto del botón de acción"
    required: true
  webhook_url:
    description: "URL del cananl de Teams"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        
        export TITLE="${{ inputs.title }}"
        export MESSAGE="${{ inputs.message }}"
        export STATE="${{ inputs.state }}"
        export COLOR="${{ inputs.color }}"
        export ACTION_TITLE="${{ inputs.action_title }}"
        export REPO="${{ github.repository }}"
        export REF="${{ github.ref_name }}"
        export SERVER_URL="${{ github.server_url }}"
        export RUN_ID="${{ github.run_id }}"

        envsubst < .github/templates/payload.json > payload_final.json

        curl -X POST -H "Content-Type: application/json" \
          -d @payload_final.json \
          "${{ inputs.webhook_url }}"
