name: "Notificar a Teams"
description: "Envía notificaciones a Microsoft Teams con AdaptiveCards"
inputs:
  title:
    description: "Título del mensaje"
    required: true
  message:
    description: "Mensaje a mostrar"
    required: true
  state:
    description: "Estado final (SUCCESS/FAILED)"
    required: true
  color:
    description: "Color de estado (Good/Attention)"
    required: true
  action_title:
    description: "Texto del botón de acción"
    required: true
  webhook_url: 
    description: "URL del Canal de Teams"
    required: true
  
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        PAYLOAD=$(cat <<'EOF'
{
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.4",
        "body": [
          {
            "type": "TextBlock",
            "text": "${{ inputs.title }}",
            "weight": "Bolder",
            "size": "Large",
            "color": "${{ inputs.color }}"
          },
          {
            "type": "TextBlock",
            "text": "${{ inputs.message }}",
            "wrap": true
          },
          {
            "type": "FactSet",
            "facts": [
              {"title": "Estado final:", "value": "${{ inputs.state }}"},
              {"title": "Repositorio:", "value": "${{ github.repository }}"},
              {"title": "Rama:", "value": "${{ github.ref_name }}"}
            ]
          }
        ],
        "actions": [
          {
            "type": "Action.OpenUrl",
            "title": "${{ inputs.action_title }}",
            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
        ]
      }
    }
  ]
}
EOF
)
        curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ inputs.webhook_url }}"