name: "Notificar a Teams"
description: "Envía notificaciones a Microsoft Teams con AdaptiveCards"

inputs:
  title:
    required: true
  message:
    required: true
  state:
    required: true
  color:
    required: false
    default: "Default"
  action_title:
    required: true
  webhook_url:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Variables de entorno a sustituir en el template
        export TITLE="${{ inputs.title }}"
        export MESSAGE="${{ inputs.message }}"
        export STATE="${{ inputs.state }}"
        export COLOR="${{ inputs.color }}"
        export ACTION_TITLE="${{ inputs.action_title }}"
        export REPO="${{ github.repository }}"
        export REF="${{ github.ref_name }}"
        export SERVER_URL="${{ github.server_url }}"
        export RUN_ID="${{ github.run_id }}"

        # Crear payload final desde la plantilla
        envsubst < .github/templates/payload.json > payload_final.json

        # Enviar a Teams
        curl -X POST -H "Content-Type: application/json" \
          -d @payload_final.json \
          "${{ inputs.webhook_url }}"
