name: Lab DSO
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "obtener ultima version del codigo"
        uses: actions/checkout@v3
      
      - name: Instalar java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Hacer ejecutable el archivo mvnw
        run: chmod +x ./mvnw

      - name: Compilacion
        run: ./mvnw clean install -DskipTests

      - name: Evaluacion SCA
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "WebGoat"
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableRetireJS


      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./"    

      - name: Ambiente de prueba con docker
        run: docker build -t scidevsecops/my-app:latest .

      - name: Evaluando con Aqua trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'scidevsecops/my-app:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m
      
      
      - name: "Obtener Arachni"
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          rm -fr arachni-*.tar.gz

      - name: "Ejecutar contenedor"
        run: |
          docker run -d -p 8080:8080 -p 9090:9090 --name webgoat-container scidevsecops/my-app:latest

      - name: "Obtener IP del contenedor"
        id: container_ip
        run: |
          IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' webgoat-container)
          echo "IP del contenedor: $IP"
          echo "CONTAINER_IP=$IP" >> $GITHUB_ENV
          sleep 20

      - name: Escaneo con Arachni
        run: |
          cd arachni-*/bin
          ./arachni http://${{env.CONTAINER_IP}}:8080/WebGoat \
          --output-verbose \
          --scope-include-subdomains \
          --report-save-path=scan.afr
        


      

      
