name: Lab DSO
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   
      contents: read 
      packages: write

    steps:
      - name: "obtener ultima version del codigo"
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::976954139503:role/capacitacion-jairo-2025
          aws-region: us-east-1
      
      - name: Instalar java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Hacer ejecutable el archivo mvnw
        run: chmod +x ./mvnw
          
      - name: Crea carpeta de los reportes
        run: mkdir 'reports'

      - name: Compilacion
        run: ./mvnw clean install -DskipTests

      - name: Evaluacion SCA
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "WebGoat"
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableRetireJS


      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./" -o="json" -O="reports/horusec-report.json"

      - name: Ambiente de prueba con docker
        run: docker build -t scidevsecops/my-app:latest .

      - name: Evaluando con Aqua trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'scidevsecops/my-app:latest'
          format: 'table'
          output: 'reports/trivy-report.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m
      
      
      - name: "Obtener Arachni"
        run: |
          wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          rm -fr arachni-*.tar.gz

      - name: "Ejecutar contenedor"
        run: |
          docker run -d -p 8080:8080 -p 9090:9090 --name webgoat-container scidevsecops/my-app:latest
          sleep 20

      - name: Escaneo con Arachni
        run: |
          cd arachni-*/bin
          ./arachni http://172.17.0.2:8080/WebGoat \
          --output-verbose \
          --scope-include-subdomains \
          --report-save-path=../../reports/scan.afr

      - name: Generar reporte HTML con Arachni Reporter
        run: |
          cd arachni-*/bin
          ./arachni_reporter ../../reports/scan.afr --reporter=html:outfile=../../reports/scan.html
      
      - name: Detener contenedor de aplicacion
        run: docker stop webgoat-container

      - name: Comprimiendo la carpeta de los Reportes
        run: zip -r reports.zip reports

      - name: Reportes de Herramientas
        uses: actions/upload-artifact@v4
        with: 
          name: Reportes
          retention-days: 1
          path: reports.zip
      
      - name: Credencial AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::976954139503:role/capacitacion-jairo-2025
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t webgoat .

      - name: Tag image
        run: |
          aws_account_id=$(aws sts get-caller-identity --query Account --output text)
          docker tag webgoat:latest $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/webgoat-repo:latest

      - name: Push to ECR
        run: |
          aws_account_id=$(aws sts get-caller-identity --query Account --output text)
          docker push $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/webgoat-repo:latest

      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"

      - name: Iniciar terraform
        run: terraform init

      - name: Aplicar terraform
        run: terraform apply -auto-approve
