name: Lab DSO
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "obtener ultima version del codigo"
        uses: actions/checkout@v3
      
      - name: Instalar java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Hacer ejecutable el archivo mvnw
        run: chmod +x ./mvnw

      - name: Compilacion
        run: ./mvnw clean install

      - name: Evaluacion SCA
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "WebGoat"
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableRetireJS


      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./"    

      # Ambiente de prueba con docker, crear la imagen del ambiente y ejecutar el contenedor apartir del dockerfile 
      # ejecutando el ls desde CMD

      - name: Ambiente de prueba con docker
        run: docker build -t scidevsecops/my-app:latest .

      - name: Evaluando con Aqua trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'scidevsecops/my-app:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          


      

      
