name: Lab DSO
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "obtener ultima version del codigo"
        uses: actions/checkout@v3
      
      - name: Instalar java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Hacer ejecutable el archivo mvnw
        run: chmod +x ./mvnw

      - name: Compilacion
        run: ./mvnw clean install

      - name: Evaluacion SCA
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "WebGoat"
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableRetireJS

      - name: Comprobar reportes Dependency
        run: ls -ltr ./reports

      
