name: Lab DSO
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Compilar
        run: "echo 'compilar'"

      - name: Probar
        run: echo "probar"

      - name: desplegar
        run: echo "desplegar"
