name: Lab DSO

on:
  push:
    branches:
      - main

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   
      contents: read 
      packages: write

    steps:
      # ========== NOTIFICACIÓN DE INICIO ==========
      - name: Notificar inicio del workflow
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🟡 Workflow Iniciado - Lab DSO",
                      "weight": "Bolder",
                      "size": "Large",
                      "color": "Warning"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Repositorio:** ${{ github.repository }}\n**Rama:** ${{ github.ref_name }}\n**Commit:** ${{ github.sha }}\n**Iniciado por:** ${{ github.actor }}",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Estado:", "value": "Iniciando configuración inicial..."},
                        {"title": "Workflow:", "value": "${{ github.workflow }}"}
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "Seguir Workflow",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: "obtener ultima version del codigo"
        uses: actions/checkout@v3

      # ========== CONFIGURACIÓN INICIAL ==========
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::976954139503:role/capacitacion-jairo-2025
          aws-region: us-east-1
      
      - name: Instalar java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Hacer ejecutable el archivo mvnw
        run: chmod +x ./mvnw
          
      - name: Crea carpeta de los reportes
        run: mkdir 'reports'

      # ========== NOTIFICAR PROGRESO ==========
      - name: Notificar configuración completada
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "✅ Configuración inicial completada",
                      "weight": "Bolder",
                      "size": "Medium",
                      "color": "Good"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Java, AWS y Maven configurados correctamente",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Próximo paso:", "value": "Compilación Maven"},
                        {"title": "Tiempo:", "value": "'"$(date)"'"}
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: Compilacion
        run: ./mvnw clean install -DskipTests

      - name: Notificar compilación exitosa
        if: success()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "✅ Compilación exitosa",
                      "weight": "Bolder",
                      "size": "Medium",
                      "color": "Good"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Maven build completado sin errores",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Próximo:", "value": "Análisis SCA (Dependency Check)"},
                        {"title": "Estado:", "value": "Success"}
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: Notificar error en compilación
        if: failure()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "❌ ERROR en compilación",
                      "weight": "Bolder",
                      "size": "Medium",
                      "color": "Attention"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Paso fallido: Maven build - Revisar dependencias y código fuente",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Workflow:", "value": "${{ github.workflow }}"},
                        {"title": "Repositorio:", "value": "${{ github.repository }}"},
                        {"title": "Hora del error:", "value": "'"$(date)"'"}
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "Ver Logs de Error",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      # ========== ANÁLISIS DE SEGURIDAD ==========
      - name: Evaluacion SCA
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: "WebGoat"
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --disableRetireJS
            --disableCentral

      - name: Notificar SCA completado
        if: success()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🔍 Análisis SCA completado",
                      "weight": "Bolder",
                      "size": "Medium"
                    },
                    {
                      "type": "TextBlock",
                      "text": "OWASP Dependency Check finalizado",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Herramienta:", "value": "Dependency Check"},
                        {"title": "Próximo:", "value": "Horusec Security"}
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p="./" -o="json" -O="reports/horusec-report.json"

      - name: Notificar Horusec completado
        if: success()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🔒 Análisis Horusec completado",
                      "weight": "Bolder",
                      "size": "Medium"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Escaneo de seguridad con Horusec finalizado",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Herramienta:", "value": "Horusec Security"},
                        {"title": "Próximo:", "value": "Build Docker"}
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      # ========== DOCKER Y VULNERABILIDADES ==========
      - name: Ambiente de prueba con docker
        run: docker build -t scidevsecops/my-app:latest .

      - name: Notificar Docker build exitoso
        if: success()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🐳 Imagen Docker construida",
                      "weight": "Bolder",
                      "size": "Medium"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Tag: scidevsecops/my-app:latest",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Próximo:", "value": "Escaneo Trivy"},
                        {"title": "Estado:", "value": "Success"}
                      ]
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      - name: Evaluando con Aqua trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'scidevsecops/my-app:latest'
          format: 'table'
          output: 'reports/trivy-report.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m

      # ... continúa con el resto de tus pasos originales ...

      # ========== NOTIFICACIÓN FINAL ==========
      - name: Notificar resultado final del workflow
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            PAYLOAD='{
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": [
                      {
                        "type": "TextBlock",
                        "text": "🎉 Workflow Lab DSO Completado",
                        "weight": "Bolder",
                        "size": "Large",
                        "color": "Good"
                      },
                      {
                        "type": "TextBlock",
                        "text": "Todos los análisis de seguridad finalizados exitosamente",
                        "wrap": true
                      },
                      {
                        "type": "FactSet",
                        "facts": [
                          {"title": "Estado final:", "value": "SUCCESS"},
                          {"title": "Repositorio:", "value": "${{ github.repository }}"},
                          {"title": "Rama:", "value": "${{ github.ref_name }}"},
                          {"title": "Herramientas ejecutadas:", "value": "6 análisis"},
                          {"title": "Despliegue:", "value": "ECR + Terraform"}
                        ]
                      }
                    ],
                    "actions": [
                      {
                        "type": "Action.OpenUrl",
                        "title": "Ver Detalles Completos",
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                    ]
                  }
                }
              ]
            }'
          else
            PAYLOAD='{
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": [
                      {
                        "type": "TextBlock",
                        "text": "💥 Workflow Lab DSO Fallido",
                        "weight": "Bolder",
                        "size": "Large",
                        "color": "Attention"
                      },
                      {
                        "type": "TextBlock",
                        "text": "Workflow completado con errores - Revisar logs",
                        "wrap": true
                      },
                      {
                        "type": "FactSet",
                        "facts": [
                          {"title": "Estado final:", "value": "FAILED"},
                          {"title": "Repositorio:", "value": "${{ github.repository }}"},
                          {"title": "Acción requerida:", "value": "Revisar logs del workflow"}
                        ]
                      }
                    ],
                    "actions": [
                      {
                        "type": "Action.OpenUrl",
                        "title": "Diagnosticar Errores",
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                    ]
                  }
                }
              ]
            }'
          fi
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"

      # ========== MANEJO DE ERRORES GLOBAL ==========
      - name: Notificar error crítico
        if: failure()
        run: |
          PAYLOAD='{
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.4",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🚨 ERROR CRÍTICO EN WORKFLOW",
                      "weight": "Bolder",
                      "size": "Large",
                      "color": "Attention"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Workflow Lab DSO ha fallado - Se requiere intervención",
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {"title": "Workflow:", "value": "${{ github.workflow }}"},
                        {"title": "Repositorio:", "value": "${{ github.repository }}"},
                        {"title": "Hora del error:", "value": "'"$(date)"'"}
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "Revisar Logs",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              }
            ]
          }'
          
          curl -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"